# Generated by Django 2.1.2 on 2020-03-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'managed': False},
        ),
    ]
