# Generated by Django 2.1.2 on 2020-03-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20200303_2252'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='list',
            table='list',
        ),
    ]
