# Generated by Django 2.1.2 on 2020-03-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200303_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
    ]
