# Generated by Django 2.1.2 on 2020-03-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20200303_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'managed': False},
        ),
    ]
